### ISSUE TITLE
Union/Dict Type

### ISSUE THREAD

**Issue by jakobkogler** [dataclass-mapper/dataclass-mapper#4]

**Comment by filwaline** [comment]
Since py310, wittern `Optional[T]` as `T | None` is much convenience, but this libary don't handle it well. 
Please support Union type or put a ***BIG ALERT*** about it, this kind of bug is confusing.

**Comment by jakobkogler** [comment]
@filwaline Can you please describe the problem in a bit more detail.

In general Union types are not supported. And with that I mean, that you can't map an `int` to an `int | float` (even though such a conversion is unproblematic). And yes, the error message in such a case is really bad. I'll try to fix it in the next days.

However, the current library already supports writing `int | None` instead of `Optional[int]` (because for Python both expressions are identical). And it supports those already a long time.
E.g. the following works for Python 3.10.9:
```py
from pydantic import BaseModel
from dataclass_mapper import mapper, map_to

class Bar(BaseModel):
    x: int | None

@mapper(Bar)
class Foo(BaseModel):
    x: int | None

obj = Foo(x=5)
print(obj)
print(map_to(obj, Bar))
```

The following however doesn't work, however that's intentional and the error message explains the problem (if the source class has the value `None`, then mapping it to an `int` is not possible):
```py
from pydantic import BaseModel
from dataclass_mapper import mapper, map_to

class Bar(BaseModel):
    x: int

@mapper(Bar)
class Foo(BaseModel):
    x: int | None

obj = Foo(x=5)
print(obj)
print(map_to(obj, Bar))
```
```
    source_code.add_mapping(
  File "/home/jakob/tmp/asdfsakfadsdf/.venv/lib/python3.10/site-packages/dataclass_mapper/mapping_method.py", line 165, in add_mapping
    options = AssignmentOptions.from_Metas(
  File "/home/jakob/tmp/asdfsakfadsdf/.venv/lib/python3.10/site-packages/dataclass_mapper/mapping_method.py", line 88, in from_Metas
    raise TypeError(f"{source} of '{source_cls.name}' cannot be converted to {target}")
TypeError: 'x' of type 'Optional[int]' of 'Foo' cannot be converted to 'x' of type 'int'
```

**Comment by filwaline** [comment]
```python
from pydantic import BaseModel
from pydantic.dataclasses import dataclass
# from dataclasses import dataclass
from dataclass_mapper import map_to, mapper, mapper_from


@dataclass
class Foo:
    abc: str | None


@mapper_from(Foo)
@mapper(Foo)
class Bar(BaseModel):
    abc: str | None


obj = Foo(abc=None)
print(map_to(obj, Bar))
```
```
Traceback (most recent call last):
  File "/home/rusty/playground/playground/pep604.py", line 13, in <module>
    @mapper(Foo)
     ^^^^^^^^^^^
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/mapper.py", line 125, in wrapped
    add_mapper_function(
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/mapper.py", line 159, in add_mapper_function
    map_code, factories, context = _make_mapper(
                                   ^^^^^^^^^^^^^
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/mapper.py", line 85, in _make_mapper
    source_code.add_mapping(
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/mapping_method.py", line 165, in add_mapping
    options = AssignmentOptions.from_Metas(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/mapping_method.py", line 88, in from_Metas
    raise TypeError(f"{source} of '{source_cls.name}' cannot be converted to {target}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/fieldmeta.py", line 41, in __repr__
    return f"'{self.name}' of type '{self.type_string}'"
                                     ^^^^^^^^^^^^^^^^
  File "/home/rusty/.cache/pypoetry/virtualenvs/playground-WkNktJap-py3.11/lib/python3.11/site-packages/dataclass_mapper/fieldmeta.py", line 35, in type_string
    type_name = cast(str, self.type.__name__)
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__name__'. Did you mean: '__ne__'?
```


It seems like a corner-case, map bewteen `dataclasses.dataclass, pydantic.dataclasses.dataclass` and `pydantic.BaseModel`, will produce this error. 

---

env info

MS WSL2 Ubuntu20.04
Python   3.11.1
dataclass-mapper  1.5.1 
pydantic  1.10.4
